[package]
name = "bliss-html"
description = "Bliss HTML parser"
documentation = "https://docs.rs/bliss-html"
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# Bliss dependencies
bliss-dom = { workspace = true }
bliss-traits = { workspace = true }

# Servo dependencies
html5ever = { workspace = true }
xml5ever = { workspace = true }