[package]
name = "bliss-paint"
description = "Paint a Bliss Document using anyrender"
documentation = "https://docs.rs/bliss-paint"
version = "0.2.99"
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["svg"]
tracing = ["dep:tracing"]
svg = ["dep:anyrender_svg", "dep:usvg", "bliss-dom/svg"]

[dependencies]
# Bliss dependencies
anyrender = { workspace = true }
anyrender_svg = { workspace = true, optional = true }
bliss-traits = { workspace = true }
bliss-dom = { workspace = true }

# Servo dependencies
style = { workspace = true }
euclid = { workspace = true }

# DioxusLabs dependencies
taffy = { workspace = true }

# Linebender + WGPU dependencies
parley = { workspace = true }
color = { workspace = true }
peniko = { workspace = true }
kurbo = { workspace = true }
usvg = { workspace = true, optional = true }

# Other dependencies
tracing = { workspace = true, optional = true }
