[package]
name = "debug_timer"
description = "Utilities for simple timings"
version = "0.1.3"
homepage = "https://github.com/nixpt/bliss-engine"
repository = "https://github.com/nixpt/bliss-engine"
documentation = "https://docs.rs/debug_timer"
license.workspace = true
edition = "2024"

[features]
enable = []
